### ISSUE TITLE
Language support and code editing [bug,enhancement]

### ISSUE THREAD

**Issue by ghost** [Busybasket/ASCIIConverter#1]
For ease of use, I recommend that the repository be translated into English, however, a small code edit can be made.
we can simply use lenDeger = len(Cdeger)'' instead of 'len(Cdeger)' in the code. I simply recommend these

**Comment by eminnates** [comment]
> For ease of use, I recommend that the repository be translated into English, however, a small code edit can be made.
> we can simply use lenDeger = len(Cdeger)'' instead of 'len(Cdeger)' in the code. I simply recommend these

thanks

**Comment by eminnates** [comment]
> For ease of use, I recommend that the repository be translated into English, however, a small code edit can be made.
> we can simply use lenDeger = len(Cdeger)'' instead of 'len(Cdeger)' in the code. I simply recommend these

you forgot to translate some parts, I fixed them

**Comment by ghost** [comment]
you are awesome thank you
